include ../utils/Makefrag

SOURCE_URL = https://ftp.osuosl.org/pub/xiph/releases/vorbis/libvorbis-1.3.7.tar.xz
SOURCE_FILE = libvorbis-1.3.7.tar.xz
SOURCE_DIR = libvorbis-1.3.7
CONFIG_ARGS = --prefix=$(PREFIX) --host aarch64-unknown-linux-musl --enable-shared

$(eval $(call define_autotools_package))
