include ../utils/Makefrag

SOURCE_URL = https://downloads.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz
SOURCE_FILE = lame-3.100.tar.gz
SOURCE_DIR = lame-3.100
CONFIG_ARGS = --prefix=$(PREFIX) --host aarch64-unknown-linux-musl --enable-shared

$(eval $(call define_autotools_package))
