include ../utils/Makefrag

SOURCE_URL = https://ftpmirror.gnu.org/gnu/libunistring/libunistring-1.3.tar.xz
SOURCE_FILE = libunistring-1.3.tar.xz
SOURCE_DIR = libunistring-1.3
CONFIG_ARGS = --prefix=$(PREFIX) --disable-static --enable-shared --host aarch64-unknown-linux-musl

$(eval $(call define_autotools_package))
