include ../utils/Makefrag

SOURCE_URL = $(GNU_MIRROR)/gnu/tar/tar-1.35.tar.xz
SOURCE_FILE = tar-1.35.tar.xz
SOURCE_DIR = tar-1.35
CONFIG_ARGS = --prefix=$(PREFIX) --host $(OHOS_ARCH)-unknown-linux-musl --disable-nls

$(eval $(call define_autotools_package))
