include ../utils/Makefrag

SOURCE_URL = https://ftpmirror.gnu.org/gnu/make/make-4.4.1.tar.gz
SOURCE_FILE = make-4.4.1.tar.gz
SOURCE_DIR = make-4.4.1
CONFIG_ARGS = --prefix=$(PREFIX) --host aarch64-unknown-linux-musl

$(eval $(call define_autotools_package))
