include ../utils/Makefrag

SOURCE_URL = $(GNU_MIRROR)/gnu/make/make-4.4.1.tar.gz
SOURCE_FILE = make-4.4.1.tar.gz
SOURCE_DIR = make-4.4.1
CONFIG_ARGS = --prefix=$(PREFIX) --host $(OHOS_ARCH)-unknown-linux-musl

$(eval $(call define_autotools_package))
