include ../utils/Makefrag

SOURCE_URL = $(GNU_MIRROR)/gnu/libidn/libidn2-2.3.8.tar.gz
SOURCE_FILE = libidn2-2.3.8.tar.gz
SOURCE_DIR = libidn2-2.3.8
CONFIG_ARGS = --prefix=$(PREFIX) --disable-static --enable-shared --host $(OHOS_ARCH)-unknown-linux-musl

$(eval $(call define_autotools_package))
