include ../utils/Makefrag

SOURCE_URL = https://ftpmirror.gnu.org/gnu/gettext/gettext-0.25.tar.xz
SOURCE_FILE = gettext-0.25.tar.xz
SOURCE_DIR = gettext-0.25
CONFIG_ARGS = --prefix=$(PREFIX) --disable-static --enable-shared --host aarch64-unknown-linux-musl

$(eval $(call define_autotools_package))
