include ../utils/Makefrag

SOURCE_URL = https://downloads.xiph.org/releases/ogg/libogg-1.3.6.tar.gz
SOURCE_FILE = libogg-1.3.6.tar.gz
SOURCE_DIR = libogg-1.3.6
CONFIG_ARGS = --prefix=$(PREFIX) --host aarch64-unknown-linux-musl --enable-shared

$(eval $(call define_autotools_package))
