include ../utils/Makefrag

SOURCE_URL = https://code.videolan.org/videolan/x264/-/archive/stable/x264-stable.tar.bz2
SOURCE_FILE = x264-stable.tar.bz2
SOURCE_DIR = x264-stable
CONFIG_ARGS = --prefix=$(PREFIX) --host=$(OHOS_ARCH)-unknown-linux-musl --enable-shared

$(eval $(call define_autotools_package))
