include ../utils/Makefrag

SOURCE_URL = https://github.com/webmproject/libvpx/archive/refs/tags/v1.15.2.tar.gz
SOURCE_FILE = v1.15.2.tar.gz
SOURCE_DIR = libvpx-1.15.2
CONFIG_ARGS = --prefix=$(PREFIX) --enable-shared

$(eval $(call define_autotools_package))
